[supervisord]
nodaemon=true

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=5

[program:laravel-worker]
command=php /var/www/artisan queue:work database --sleep=3 --tries=3
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/www/storage/logs/laravel-queue.log
redirect_stderr=true
